name = "nodewarden"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# KV Namespace for storing vault data
[[kv_namespaces]]
binding = "VAULT"
id = "a0eb412c2f4f4c89b5810a0c6bbe9c17"

# R2 Bucket for storing attachments
[[r2_buckets]]
binding = "ATTACHMENTS"
bucket_name = "nodewarden-attachments"
